name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate Dockerfile
      - name: Generate Dockerfile
        run: |
          echo "FROM python:3.9-slim" > CodeGenAiApi/Dockerfile
          echo "WORKDIR /app" >> CodeGenAiApi/Dockerfile
          echo "COPY . /app" >> CodeGenAiApi/Dockerfile
          echo "RUN pip install -r requirements.txt" >> CodeGenAiApi/Dockerfile
          echo "CMD [\"python\", \"app.py\"]" >> CodeGenAiApi/Dockerfile

      # Step 3: Log in to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: abhidevcr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./CodeGenAiApi
          file: ./CodeGenAiApi/Dockerfile
          push: true
          tags: abhidevcr.azurecr.io/codegen-api:latest
